### ISSUE TITLE
blob assignments

### ISSUE THREAD

**Issue by Makosak** [brettjgoldstein/blobs#2]
I'm not able to see blob assignments, in the final steps of the tutorial.

b.assignments

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-e5f6aaeef3ef> in <module>()
----> 1 b.assignments

AttributeError: Blobs instance has no attribute 'assignments'

**Comment by jiajunshen** [comment]
try:

cl.assignments

**Comment by brettjgoldstein** [comment]
What resolved this?

On Mon, Jul 13, 2015 at 6:14 PM, Jonathan Giuffrida <notifications@github.com> wrote:

Closed #2<https://github.com/brettjgoldstein/blobs/issues/2>.

**Comment by lucaluca** [comment]
`assignments` is a property of `Cluster_blobs`, not of `Blobs`. For blob assignments, use `b.r.area2region`, or `b.regions`.
