### ISSUE TITLE
Blobs building error

### ISSUE THREAD

**Issue by Makosak** [brettjgoldstein/blobs#3]
I'm getting an error at the first stage of buliding blobs. I've loaded and joined my CSV data to tractIDs, and getting error with this line -- it starts to "think" and after a few seconds the error spits out.

In [20]: b = blobs.Blobs(d, 'Pop2012', 10000, iterations=1)

['GeoID2', 'Pop2012', 'Male', 'Female', 'Under5', 'Child2012', 'Teen2012', 'MdnAge2012', 'AgeOver21', 'AgeOver65', 'Whte2012', 'Blck2012', 'AI2012', 'Asn2012', 'NHPI2012', 'OthrRc2012', 'Hisp2012', 'UnEmpl2012', 'WrkCmtCar2012', 'WrkCmtTm2012', 'HHLDS2012', 'SNAP2012', 'Famlies2012', 'MedIncome2012', 'MeanIncome2012', 'HlthCvrg2012', 'ChldPvtyPrc2012', 'PvtyPrc2012']

### CREATING BLOBS FROM 28 VARIABLES ###
    PARAMETERS:
     # Minimum Pop2012 in each blob: 10000
     # Iterations: 1
     # Method: equal votes
     # Plot blobs: True
     # Save blobs data: False

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-d049d9bc02ee> in <module>()
      1 # Create blobs minimum population of 10,000 in each blob. This calls a Pop-Up Window with the Map.
----> 2 b = blobs.Blobs(d, 'Pop2012', 10000, iterations=1)

/Users/Makosak/code/blobs/blobs.pyc in __init__(self, bd, floor_var, floor, vars_to_use, iterations, method, weights, initial, plot, savedata, plot_values, verbose)
    364         self.regions = None
    365         self.blobs_data = None
--> 366         self.build_blobs()
    367 
    368 

/Users/Makosak/code/blobs/blobs.pyc in build_blobs(self)
    404             times.append(end - start)
    405             current_time.append(end)
--> 406             current_score = r.objective_function()
    407             solutions.append(current_score)
    408             num_blobs.append(r.k)

/Users/Makosak/anaconda/lib/python2.7/site-packages/pysal/region/maxp.pyc in objective_function(self, solution)
    348         # on. solution does not have to be exhaustive
    349         if not solution:
--> 350             solution = self.regions
    351         wss = 0
    352         for region in solution:

AttributeError: Maxp instance has no attribute 'regions'

**Comment by jiajunshen** [comment]
This usually means that initial_solution() in the maxp algorithm failed to find a solution that meets the requirements. 

The following reasons that could cause this:
1. Floor variable is set too high. In your case, the population is only 1000, which should be fine.
2. The values of the floor variable are not passing into the maxp correctly, causing the maxp algorithm not be able to find solution to meet the floor variable requirement. Reasons that cause this could be:
          a. The order of your CSV data doesn't match the order of the regions in your shape file.
          b. The indices of your ordered CSV data are out of bounds. The value of an index should sit     between 0 to number of regions.

I would recommend check your CSV data and inspect the values of the local variables in the check_floor() function inside the maxp algorithm.

Hope this will help!

**Comment by lucaluca** [comment]
It's most likely to be 2(a) - take a look at [configure.py](https://github.com/brettjgoldstein/blobs/blob/master/configure.py) for an example of how I matched up a shapefile to new data. It has to be in the same order. 

We should probably catch this error more gracefully to specify what the problem is. A third thing that could cause this is if the shapefile's polygons are not all one contiguous shape - "islands" could exist that are too small to meet the floor variable so that no solution can be found.

**Comment by Makosak** [comment]
Super, thanks guys! I'll try to figure this out by tomorrow and will close
out if it works -- this makes sense!!

**Comment by Makosak** [comment]
Closing this, but we should probably open another one to create a better error message...

**Comment by meemking** [comment]
please do open a new one with specifics, Marynia. Thanks!

On Wed, Sep 23, 2015 at 4:14 PM, Marynia <notifications@github.com> wrote:

> Closed #3 <https://github.com/brettjgoldstein/blobs/issues/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettjgoldstein/blobs/issues/3#event-417463803>.
>



-- 
Maggie King
email: Maggiek@uchicago.edu
phone: (574) 286-9389
